# File .chipperci.yml, which goes in the root of your repository
version: 1

environment:
  php: 8.1    # 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2
  node: 16    # 6, 8, 10, 12, 14, 16, 18

services:
  - mysql: 5.7

pipeline:
  - name: Setup
    cmd: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      
  - name: Enable Pcov
    cmd: sudo phpenmod pcov

  - name: Run Tests
    cmd: php -d pcov.enabled=1 -d memory_limit=4G vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml tests
    
  - name: Coverage Upload
    cmd: curl -Ls https://raw.githubusercontent.com/getOtterWise/bash-uploader/main/uploader.sh | bash -s -- --repo-token $OTTERWISE_TOKEN --verbose true --ignore-errors true
